#ifndef __HOB_KRB5_ERR_TABS
#define __HOB_KRB5_ERR_TABS
#ifdef _WIN32
#pragma once
#endif
const char *heim_error_strings[141]= {
    "Error parsing log destination",
    "Failed to convert v4 principal",
    "Salt type is not supported by enctype",
    "Host not found",
    "Operation not supported",
    "End of file",
    "Failed to get the master key",
    "Unacceptable service used",
    "Reserved heim error (8)",
    "Reserved heim error (9)",
    "Reserved heim error (10)",
    "Reserved heim error (11)",
    "Reserved heim error (12)",
    "Reserved heim error (13)",
    "Reserved heim error (14)",
    "Reserved heim error (15)",
    "Reserved heim error (16)",
    "Reserved heim error (17)",
    "Reserved heim error (18)",
    "Reserved heim error (19)",
    "Reserved heim error (20)",
    "Reserved heim error (21)",
    "Reserved heim error (22)",
    "Reserved heim error (23)",
    "Reserved heim error (24)",
    "Reserved heim error (25)",
    "Reserved heim error (26)",
    "Reserved heim error (27)",
    "Reserved heim error (28)",
    "Reserved heim error (29)",
    "Reserved heim error (30)",
    "Reserved heim error (31)",
    "Reserved heim error (32)",
    "Reserved heim error (33)",
    "Reserved heim error (34)",
    "Reserved heim error (35)",
    "Reserved heim error (36)",
    "Reserved heim error (37)",
    "Reserved heim error (38)",
    "Reserved heim error (39)",
    "Reserved heim error (40)",
    "Reserved heim error (41)",
    "Reserved heim error (42)",
    "Reserved heim error (43)",
    "Reserved heim error (44)",
    "Reserved heim error (45)",
    "Reserved heim error (46)",
    "Reserved heim error (47)",
    "Reserved heim error (48)",
    "Reserved heim error (49)",
    "Reserved heim error (50)",
    "Reserved heim error (51)",
    "Reserved heim error (52)",
    "Reserved heim error (53)",
    "Reserved heim error (54)",
    "Reserved heim error (55)",
    "Reserved heim error (56)",
    "Reserved heim error (57)",
    "Reserved heim error (58)",
    "Reserved heim error (59)",
    "Reserved heim error (60)",
    "Reserved heim error (61)",
    "Reserved heim error (62)",
    "Reserved heim error (63)",
    "Certificate missing",
    "Private key missing",
    "No valid certificate authority",
    "Certificate invalid",
    "Private key invalid",
    "Reserved heim error (69)",
    "Reserved heim error (70)",
    "Reserved heim error (71)",
    "Reserved heim error (72)",
    "Reserved heim error (73)",
    "Reserved heim error (74)",
    "Reserved heim error (75)",
    "Reserved heim error (76)",
    "Reserved heim error (77)",
    "Reserved heim error (78)",
    "Reserved heim error (79)",
    "Reserved heim error (80)",
    "Reserved heim error (81)",
    "Reserved heim error (82)",
    "Reserved heim error (83)",
    "Reserved heim error (84)",
    "Reserved heim error (85)",
    "Reserved heim error (86)",
    "Reserved heim error (87)",
    "Reserved heim error (88)",
    "Reserved heim error (89)",
    "Reserved heim error (90)",
    "Reserved heim error (91)",
    "Reserved heim error (92)",
    "Reserved heim error (93)",
    "Reserved heim error (94)",
    "Reserved heim error (95)",
    "Reserved heim error (96)",
    "Reserved heim error (97)",
    "Reserved heim error (98)",
    "Reserved heim error (99)",
    "Reserved heim error (100)",
    "Reserved heim error (101)",
    "Reserved heim error (102)",
    "Reserved heim error (103)",
    "Reserved heim error (104)",
    "Reserved heim error (105)",
    "Reserved heim error (106)",
    "Reserved heim error (107)",
    "Reserved heim error (108)",
    "Reserved heim error (109)",
    "Reserved heim error (110)",
    "Reserved heim error (111)",
    "Reserved heim error (112)",
    "Reserved heim error (113)",
    "Reserved heim error (114)",
    "Reserved heim error (115)",
    "Reserved heim error (116)",
    "Reserved heim error (117)",
    "Reserved heim error (118)",
    "Reserved heim error (119)",
    "Reserved heim error (120)",
    "Reserved heim error (121)",
    "Reserved heim error (122)",
    "Reserved heim error (123)",
    "Reserved heim error (124)",
    "Reserved heim error (125)",
    "Reserved heim error (126)",
    "Reserved heim error (127)",
    "unknown error from getaddrinfo",
    "address family for nodename not supported",
    "temporary failure in name resolution",
    "invalid value for ai_flags",
    "non-recoverable failure in name resolution",
    "ai_family not supported",
    "memory allocation failure",
    "no address associated with nodename",
    "nodename nor servname provided, or not known",
    "servname not supported for ai_socktype",
    "ai_socktype not supported",

    "system error returned in (int)m__errno_location_hl()",

    (( void * )0 )
};

const char *asn1_error_strings[11]= {
    "ASN.1 failed call to system time library",
    "ASN.1 structure is missing a required field",
    "ASN.1 unexpected field number",
    "ASN.1 type numbers are inconsistent",
    "ASN.1 value too large",
    "ASN.1 encoding ended unexpectedly",
    "ASN.1 identifier doesn't match expected value",
    "ASN.1 length doesn't match expected value",
    "ASN.1 badly-formatted encoding",
    "ASN.1 parse error",
    (( void * )0 )
};

const char *krb5_error_strings[250]= {
    "No error",
    "Client's entry in database has expired",
    "Server's entry in database has expired",
    "Requested protocol version not supported",
    "Client's key is encrypted in an old master key",
    "Server's key is encrypted in an old master key",
    "Client not found in Kerberos database",
    "Server not found in Kerberos database",
    "Principal has multiple entries in Kerberos database",
    "Client or server has a null key",
    "Ticket is ineligible for postdating",
    "Requested effective lifetime is negative or too short",
    "KDC policy rejects request",
    "KDC can't fulfill requested option",
    "KDC has no support for encryption type",
    "KDC has no support for checksum type",
    "KDC has no support for padata type",
    "KDC has no support for transited type",
    "Clients credentials have been revoked",
    "Credentials for server have been revoked",
    "TGT has been revoked",
    "Client not yet valid - try again later",
    "Server not yet valid - try again later",
    "Password has expired",
    "Preauthentication failed",
    "Additional pre-authentication required",
    "Requested server and ticket don't match",
    "Server principal valid for user to user only",
    "KDC Policy rejects transited path",
    "A service is not available",
    "Reserved krb5 error (30)",
    "Decrypt integrity check failed",
    "Ticket expired",
    "Ticket not yet valid",
    "Request is a replay",
    "The ticket isn't for us",
    "Ticket/authenticator don't match",
    "Clock skew too great",
    "Incorrect net address",
    "Protocol version mismatch",
    "Invalid message type",
    "Message stream modified",
    "Message out of order",
    "Invalid cross-realm ticket",
    "Key version is not available",
    "Service key not available",
    "Mutual authentication failed",
    "Incorrect message direction",
    "Alternative authentication method required",
    "Incorrect sequence number in message",
    "Inappropriate type of checksum in message",
    "Policy rejects transited path",
    "Response too big for UDP, retry with TCP",
    "Reserved krb5 error (53)",
    "Reserved krb5 error (54)",
    "Reserved krb5 error (55)",
    "Reserved krb5 error (56)",
    "Reserved krb5 error (57)",
    "Reserved krb5 error (58)",
    "Reserved krb5 error (59)",
    "Generic error (see e-text)",
    "Field is too long for this implementation",
    "Client not trusted",
    "KDC not trusted",
    "Invalid signature",
    "Key size too small/key too weak",
    "Certificate mismatch",
    "TGT for user to user required",
    "Wrong realm",
    "Ticket must be for user to user",
    "Cannot verify certificate",
    "Invalid certificate",
    "Revoked certificate",
    "Revocation status unknown",
    "Revocation status unknown",
    "Client name mismatch",
    "KDC name mismatch",
    "Reserved krb5 error (77)",
    "Reserved krb5 error (78)",
    "Reserved krb5 error (79)",
    "IAKERB proxy could not find a KDC",
    "IAKERB proxy never reeived a response from a KDC",
    "Reserved krb5 error (82)",
    "Reserved krb5 error (83)",
    "Reserved krb5 error (84)",
    "Reserved krb5 error (85)",
    "Reserved krb5 error (86)",
    "Reserved krb5 error (87)",
    "Reserved krb5 error (88)",
    "Reserved krb5 error (89)",
    "Reserved krb5 error (90)",
    "Reserved krb5 error (91)",
    "Reserved krb5 error (92)",
    "Reserved krb5 error (93)",
    "Reserved krb5 error (94)",
    "Reserved krb5 error (95)",
    "Reserved krb5 error (96)",
    "Reserved krb5 error (97)",
    "Reserved krb5 error (98)",
    "Reserved krb5 error (99)",
    "Reserved krb5 error (100)",
    "Reserved krb5 error (101)",
    "Reserved krb5 error (102)",
    "Reserved krb5 error (103)",
    "Reserved krb5 error (104)",
    "Reserved krb5 error (105)",
    "Reserved krb5 error (106)",
    "Reserved krb5 error (107)",
    "Reserved krb5 error (108)",
    "Reserved krb5 error (109)",
    "Reserved krb5 error (110)",
    "Reserved krb5 error (111)",
    "Reserved krb5 error (112)",
    "Reserved krb5 error (113)",
    "Reserved krb5 error (114)",
    "Reserved krb5 error (115)",
    "Reserved krb5 error (116)",
    "Reserved krb5 error (117)",
    "Reserved krb5 error (118)",
    "Reserved krb5 error (119)",
    "Reserved krb5 error (120)",
    "Reserved krb5 error (121)",
    "Reserved krb5 error (122)",
    "Reserved krb5 error (123)",
    "Reserved krb5 error (124)",
    "Reserved krb5 error (125)",
    "Reserved krb5 error (126)",
    "Reserved krb5 error (127)",
    "$Id: krb5_err.et,v 1.12 2004/10/14 15:30:29 lha Exp $",
    "Invalid flag for file lock mode",
    "Cannot read password",
    "Password mismatch",
    "Password read interrupted",
    "Invalid character in component name",
    "Malformed representation of principal",
    "Can't open/find configuration file",
    "Improper format of configuration file",
    "Insufficient space to return complete information",
    "Invalid message type specified for encoding",
    "Credential cache name malformed",
    "Unknown credential cache type",
    "Matching credential not found",
    "End of credential cache reached",
    "Request did not supply a ticket",
    "Wrong principal in request",
    "Ticket has invalid flag set",
    "Requested principal and ticket don't match",
    "KDC reply did not match expectations",
    "Clock skew too great in KDC reply",
    "Client/server realm mismatch in initial ticket request",
    "Program lacks support for encryption type",
    "Program lacks support for key type",
    "Requested encryption type not used in message",
    "Program lacks support for checksum type",
    "Cannot find KDC for requested realm",
    "Kerberos service unknown",
    "Cannot contact any KDC for requested realm",
    "No local name found for principal name",
    "Mutual authentication failed",
    "Replay cache type is already registered",
    "No more memory to allocate (in replay cache code)",
    "Replay cache type is unknown",
    "Generic unknown RC error",
    "Message is a replay",
    "Replay I/O operation failed XXX",
    "Replay cache type does not support non-volatile storage",
    "Replay cache name parse/format error",
    "End-of-file on replay cache I/O",
    "No more memory to allocate (in replay cache I/O code)",
    "Permission denied in replay cache code",
    "I/O error in replay cache i/o code",
    "Generic unknown RC/IO error",
    "Insufficient system space to store replay information",
    "Can't open/find realm translation file",
    "Improper format of realm translation file",
    "Can't open/find lname translation database",
    "No translation available for requested principal",
    "Improper format of translation database entry",
    "Cryptosystem internal error",
    "Key table name malformed",
    "Unknown Key table type",
    "Key table entry not found",
    "End of key table reached",
    "Cannot write to specified key table",
    "Error writing to key table",
    "Cannot find ticket for requested realm",
    "DES key has bad parity",
    "DES key is a weak key",
    "Bad encryption type",
    "Key size is incompatible with encryption type",
    "Message size is incompatible with encryption type",
    "Credentials cache type is already registered.",
    "Key table type is already registered.",
    "Credentials cache I/O operation failed XXX",
    "Credentials cache file permissions incorrect",
    "No credentials cache file found",
    "Internal file credentials cache error",
    "Error writing to credentials cache file",
    "No more memory to allocate (in credentials cache code)",
    "Bad format in credentials cache",
    "No credentials found with supported encryption types",
    "Invalid KDC option combination (library internal error)",
    "Request missing second ticket",
    "No credentials supplied to library routine",
    "Bad sendauth version was sent",
    "Bad application version was sent (via sendauth)",
    "Bad response (during sendauth exchange)",
    "Server rejected authentication (during sendauth exchange)",
    "Unsupported preauthentication type",
    "Required preauthentication key not supplied",
    "Generic preauthentication failure",
    "Unsupported replay cache format version number",
    "Unsupported credentials cache format version number",
    "Unsupported key table format version number",
    "Program lacks support for address type",
    "Message replay detection requires rcache parameter",
    "Hostname cannot be canonicalized",
    "Cannot determine realm for host",
    "Conversion to service principal undefined for name type",
    "Initial Ticket response appears to be Version 4",
    "Cannot resolve KDC for requested realm",
    "Requesting ticket can't get forwardable tickets",
    "Bad principal name while trying to forward credentials",
    "Looping detected inside krb5_get_in_tkt",
    "Configuration file does not specify default realm",
    "Bad SAM flags in obtain_sam_padata",
    "Invalid encryption type in SAM challenge",
    "Missing checksum in SAM challenge",
    "Bad checksum in SAM challenge",
    "Reserved krb5 error (229)",
    "Reserved krb5 error (230)",
    "Reserved krb5 error (231)",
    "Reserved krb5 error (232)",
    "Reserved krb5 error (233)",
    "Reserved krb5 error (234)",
    "Reserved krb5 error (235)",
    "Reserved krb5 error (236)",
    "Reserved krb5 error (237)",
    "Program called an obsolete, deleted function",
    "Reserved krb5 error (239)",
    "Reserved krb5 error (240)",
    "Reserved krb5 error (241)",
    "Reserved krb5 error (242)",
    "Reserved krb5 error (243)",
    "Reserved krb5 error (244)",
    "Invalid key generation parameters from KDC",
    "Service not available",
    "Credential cache function not supported",
    "Invalid format of Kerberos lifetime or clock skew string",
    (( void * )0 )
};

#endif //__HOB_KRB5_ERR_TABS