param(
[int]$NUMBER_OF_PROCESSORS=1,
[string]$VSDIR="C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC",
[string]$xerces_include=""
)

$old_path = $env:PATH;
$old_lib = $env:LIB;
$old_libpath = $env:LIBPATH;
$old_VSINSTALLDIR = $env:VSINSTALLDIR;
$old_cwd = pwd

function restore() {
	write-host "build-win.ps1: restoring environment"
	$env:PATH = $old_path;
	$env:LIB = $old_lib;
	$env:LIBPATH = $old_libpath;
	$env:VSINSTALLDIR = $old_VSINSTALLDIR;
	cd $old_cwd
}

function exitOnError($error) {
	if ($error -ne 0) {
		echo "build-win.ps1 failed with code $error. exiting"
		restore
		exit 1
	}
}

if ($xerces_include) {
	write-host "build-win.ps1: set XERCES_SRC to $xerces_include"
	$env:XERCES_SRC = $xerces_include
} else {
	write-host -ForegroundColor Red "build-win.ps1: warning: no xerces_include set"
}

pushd $VSDIR
& cmd /c "vcvarsall.bat x86 & set" |
foreach {
	if ($_ -match "=") {
		$v = $_.split("="); set-item -force -path "ENV:\$($v[0])"  -value "$($v[1])"
	}
}
exitOnError($LastExitCode)
popd
write-host "`nVisual Studio 2012 Command Prompt variables set." -ForegroundColor Yellow

write-host "Building Windows X86 Binaries ..."
& ..\external\gmake-3.81\bin\windows\x86\gmake.exe "-j$NUMBER_OF_PROCESSORS" "PLATFORM=WinX86" "clean" 2>&1 | out-null
exitOnError($LastExitCode)
& ..\external\gmake-3.81\bin\windows\x86\gmake.exe "-j$NUMBER_OF_PROCESSORS" "PLATFORM=WinX86"
exitOnError($LastExitCode)

pushd $VSDIR
& cmd /c "vcvarsall.bat amd64 & set" |
foreach {
	if ($_ -match "=") {
		$v = $_.split("="); set-item -force -path "ENV:\$($v[0])"  -value "$($v[1])"
	}
}
exitOnError($LastExitCode)

# append $VSDIR\bin to Path; otherwise, compiling with "/analyze"
# option fails on hobc02k (only for amd64 builds) with message
# "c1xxast : fatal error C1108: unable to find DLL: 'mspft110.dll'"
$env:Path += ";$VSDIR\bin"

popd
write-host "`nVisual Studio 2012 Command Prompt variables set." -ForegroundColor Yellow

write-host "Building Windows EM64T Binaries ..."
& ..\external\gmake-3.81\bin\windows\x86\gmake.exe "-j$NUMBER_OF_PROCESSORS" "PLATFORM=WinX64" "clean" 2>&1 | out-null
exitOnError($LastExitCode)
& ..\external\gmake-3.81\bin\windows\x86\gmake.exe "-j$NUMBER_OF_PROCESSORS" "PLATFORM=WinX64"
exitOnError($LastExitCode)

write-host "build-win.ps1: success"
restore
# SIG # Begin signature block
# MIIYAAYJKoZIhvcNAQcCoIIX8TCCF+0CAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUTxy1VgTWFtvllQXqAEPLpPll
# XXagghL3MIID7jCCA1egAwIBAgIQfpPr+3zGTlnqS5p31Ab8OzANBgkqhkiG9w0B
# AQUFADCBizELMAkGA1UEBhMCWkExFTATBgNVBAgTDFdlc3Rlcm4gQ2FwZTEUMBIG
# A1UEBxMLRHVyYmFudmlsbGUxDzANBgNVBAoTBlRoYXd0ZTEdMBsGA1UECxMUVGhh
# d3RlIENlcnRpZmljYXRpb24xHzAdBgNVBAMTFlRoYXd0ZSBUaW1lc3RhbXBpbmcg
# Q0EwHhcNMTIxMjIxMDAwMDAwWhcNMjAxMjMwMjM1OTU5WjBeMQswCQYDVQQGEwJV
# UzEdMBsGA1UEChMUU3ltYW50ZWMgQ29ycG9yYXRpb24xMDAuBgNVBAMTJ1N5bWFu
# dGVjIFRpbWUgU3RhbXBpbmcgU2VydmljZXMgQ0EgLSBHMjCCASIwDQYJKoZIhvcN
# AQEBBQADggEPADCCAQoCggEBALGss0lUS5ccEgrYJXmRIlcqb9y4JsRDc2vCvy5Q
# WvsUwnaOQwElQ7Sh4kX06Ld7w3TMIte0lAAC903tv7S3RCRrzV9FO9FEzkMScxeC
# i2m0K8uZHqxyGyZNcR+xMd37UWECU6aq9UksBXhFpS+JzueZ5/6M4lc/PcaS3Er4
# ezPkeQr78HWIQZz/xQNRmarXbJ+TaYdlKYOFwmAUxMjJOxTawIHwHw103pIiq8r3
# +3R8J+b3Sht/p8OeLa6K6qbmqicWfWH3mHERvOJQoUvlXfrlDqcsn6plINPYlujI
# fKVOSET/GeJEB5IL12iEgF1qeGRFzWBGflTBE3zFefHJwXECAwEAAaOB+jCB9zAd
# BgNVHQ4EFgQUX5r1blzMzHSa1N197z/b7EyALt0wMgYIKwYBBQUHAQEEJjAkMCIG
# CCsGAQUFBzABhhZodHRwOi8vb2NzcC50aGF3dGUuY29tMBIGA1UdEwEB/wQIMAYB
# Af8CAQAwPwYDVR0fBDgwNjA0oDKgMIYuaHR0cDovL2NybC50aGF3dGUuY29tL1Ro
# YXd0ZVRpbWVzdGFtcGluZ0NBLmNybDATBgNVHSUEDDAKBggrBgEFBQcDCDAOBgNV
# HQ8BAf8EBAMCAQYwKAYDVR0RBCEwH6QdMBsxGTAXBgNVBAMTEFRpbWVTdGFtcC0y
# MDQ4LTEwDQYJKoZIhvcNAQEFBQADgYEAAwmbj3nvf1kwqu9otfrjCR27T4IGXTdf
# plKfFo3qHJIJRG71betYfDDo+WmNI3MLEm9Hqa45EfgqsZuwGsOO61mWAK3ODE2y
# 0DGmCFwqevzieh1XTKhlGOl5QGIllm7HxzdqgyEIjkHq3dlXPx13SYcqFgZepjhq
# IhKjURmDfrYwggSjMIIDi6ADAgECAhAOz/Q4yP6/NW4E2GqYGxpQMA0GCSqGSIb3
# DQEBBQUAMF4xCzAJBgNVBAYTAlVTMR0wGwYDVQQKExRTeW1hbnRlYyBDb3Jwb3Jh
# dGlvbjEwMC4GA1UEAxMnU3ltYW50ZWMgVGltZSBTdGFtcGluZyBTZXJ2aWNlcyBD
# QSAtIEcyMB4XDTEyMTAxODAwMDAwMFoXDTIwMTIyOTIzNTk1OVowYjELMAkGA1UE
# BhMCVVMxHTAbBgNVBAoTFFN5bWFudGVjIENvcnBvcmF0aW9uMTQwMgYDVQQDEytT
# eW1hbnRlYyBUaW1lIFN0YW1waW5nIFNlcnZpY2VzIFNpZ25lciAtIEc0MIIBIjAN
# BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAomMLOUS4uyOnREm7Dv+h8GEKU5Ow
# mNutLA9KxW7/hjxTVQ8VzgQ/K/2plpbZvmF5C1vJTIZ25eBDSyKV7sIrQ8Gf2Gi0
# jkBP7oU4uRHFI/JkWPAVMm9OV6GuiKQC1yoezUvh3WPVF4kyW7BemVqonShQDhfu
# ltthO0VRHc8SVguSR/yrrvZmPUescHLnkudfzRC5xINklBm9JYDh6NIipdC6Anqh
# d5NbZcPuF3S8QYYq3AhMjJKMkS2ed0QfaNaodHfbDlsyi1aLM73ZY8hJnTrFxeoz
# C9Lxoxv0i77Zs1eLO94Ep3oisiSuLsdwxb5OgyYI+wu9qU+ZCOEQKHKqzQIDAQAB
# o4IBVzCCAVMwDAYDVR0TAQH/BAIwADAWBgNVHSUBAf8EDDAKBggrBgEFBQcDCDAO
# BgNVHQ8BAf8EBAMCB4AwcwYIKwYBBQUHAQEEZzBlMCoGCCsGAQUFBzABhh5odHRw
# Oi8vdHMtb2NzcC53cy5zeW1hbnRlYy5jb20wNwYIKwYBBQUHMAKGK2h0dHA6Ly90
# cy1haWEud3Muc3ltYW50ZWMuY29tL3Rzcy1jYS1nMi5jZXIwPAYDVR0fBDUwMzAx
# oC+gLYYraHR0cDovL3RzLWNybC53cy5zeW1hbnRlYy5jb20vdHNzLWNhLWcyLmNy
# bDAoBgNVHREEITAfpB0wGzEZMBcGA1UEAxMQVGltZVN0YW1wLTIwNDgtMjAdBgNV
# HQ4EFgQURsZpow5KFB7VTNpSYxc/Xja8DeYwHwYDVR0jBBgwFoAUX5r1blzMzHSa
# 1N197z/b7EyALt0wDQYJKoZIhvcNAQEFBQADggEBAHg7tJEqAEzwj2IwN3ijhCcH
# bxiy3iXcoNSUA6qGTiWfmkADHN3O43nLIWgG2rYytG2/9CwmYzPkSWRtDebDZw73
# BaQ1bHyJFsbpst+y6d0gxnEPzZV03LZc3r03H0N45ni1zSgEIKOq8UvEiCmRDoDR
# EfzdXHZuT14ORUZBbg2w6jiasTraCXEQ/Bx5tIB7rGn0/Zy2DBYr8X9bCT2bW+IW
# yhOBbQAuOA2oKY8s4bL0WqkBrxWcLC9JG9siu8P+eJRRw4axgohd8D20UaF5Mysu
# e7ncIAkTcetqGVvP6KUwVyyJST+5z3/Jvz4iaGNTmr1pdKzFHTx/kuDDvBzYBHUw
# ggT9MIID5aADAgECAhBZhQi7tYqz1O1izDrs/nPdMA0GCSqGSIb3DQEBCwUAMH8x
# CzAJBgNVBAYTAlVTMR0wGwYDVQQKExRTeW1hbnRlYyBDb3Jwb3JhdGlvbjEfMB0G
# A1UECxMWU3ltYW50ZWMgVHJ1c3QgTmV0d29yazEwMC4GA1UEAxMnU3ltYW50ZWMg
# Q2xhc3MgMyBTSEEyNTYgQ29kZSBTaWduaW5nIENBMB4XDTE3MDYyMTAwMDAwMFoX
# DTE5MDYyMzIzNTk1OVowgZQxCzAJBgNVBAYTAkRFMRAwDgYDVQQIDAdCYXZhcmlh
# MRMwEQYDVQQHDApDYWRvbHpidXJnMRowGAYDVQQKDBFIT0IgR21iSCAmIENvLiBL
# RzEmMCQGA1UECwwdU2VjdXJpdHkgU29mdHdhcmUgRGV2ZWxvcG1lbnQxGjAYBgNV
# BAMMEUhPQiBHbWJIICYgQ28uIEtHMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
# CgKCAQEAugWtMx5IVfkdfxPsjHV8YQSAoGqQZ0y+I441qckf3N3vvKcUBnogEUHN
# az764MRnxeUlylGEiRE/TkLq7Yfk+fdR/v5Ap/uZMDi6ltobOjjJHVuT/5rF0Cnk
# 5s8Nghh2oY5ciwS3S5yQMwUzVZSAlk0/3t4DGvZFM9F0bgz3YbZf90GPjKe2cIRX
# BmH3tacfrimUj4aV6NGBjg4Y9MRUzxkUJFT06RA31L1WqbZxxJywIXE2IPT9I88g
# 3GOTbOOhaZ7GlYqJtXTbSVbtUW7VOLe2AQmvtDh3bj9qjH7EqD5r/WYL/4k2gDOs
# vQnl6mJ1BKaHnhpHQc7G6hGecaPvvwIDAQABo4IBXTCCAVkwCQYDVR0TBAIwADAO
# BgNVHQ8BAf8EBAMCB4AwKwYDVR0fBCQwIjAgoB6gHIYaaHR0cDovL3N2LnN5bWNi
# LmNvbS9zdi5jcmwwYQYDVR0gBFowWDBWBgZngQwBBAEwTDAjBggrBgEFBQcCARYX
# aHR0cHM6Ly9kLnN5bWNiLmNvbS9jcHMwJQYIKwYBBQUHAgIwGQwXaHR0cHM6Ly9k
# LnN5bWNiLmNvbS9ycGEwEwYDVR0lBAwwCgYIKwYBBQUHAwMwVwYIKwYBBQUHAQEE
# SzBJMB8GCCsGAQUFBzABhhNodHRwOi8vc3Yuc3ltY2QuY29tMCYGCCsGAQUFBzAC
# hhpodHRwOi8vc3Yuc3ltY2IuY29tL3N2LmNydDAfBgNVHSMEGDAWgBSWO1PweTOX
# r32D7y4rzMq3hh5yZjAdBgNVHQ4EFgQU+ov69nJkvlEvjJApxodxOxWcaZIwDQYJ
# KoZIhvcNAQELBQADggEBADsA/wo3IANUCtzTZa4Id3EeAuzZJfHHaxNAPJNGcp90
# WEfVFBc3TulaM2pMvRNLGj6qbCve5LGuj4e0mnloM/KGlebMWBNU2cK7oU9vkXAG
# +j6GUSlrDhh96N8YB6oB1runSsU29o5Y1m12p8zBkzG/RB7kRWZdj5Ohia6fDQMC
# 8ZZYTNltsBLZCabTZHc7yse3KT5jYH2M+YCO5usdR389/RBYw89qrsxCOSn4sDSI
# re+t+YMOTgiwd48XPANmhZlXN5quSIZn0NRJmId5pSVIiu2qm4vQkCeSimbOShGh
# P8HPHvU2Zpknj1rqNEqvPxzRNm0SFWuKiF7l0V0c2mYwggVZMIIEQaADAgECAhA9
# eNf5dklgsmF99PAeyoYqMA0GCSqGSIb3DQEBCwUAMIHKMQswCQYDVQQGEwJVUzEX
# MBUGA1UEChMOVmVyaVNpZ24sIEluYy4xHzAdBgNVBAsTFlZlcmlTaWduIFRydXN0
# IE5ldHdvcmsxOjA4BgNVBAsTMShjKSAyMDA2IFZlcmlTaWduLCBJbmMuIC0gRm9y
# IGF1dGhvcml6ZWQgdXNlIG9ubHkxRTBDBgNVBAMTPFZlcmlTaWduIENsYXNzIDMg
# UHVibGljIFByaW1hcnkgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkgLSBHNTAeFw0x
# MzEyMTAwMDAwMDBaFw0yMzEyMDkyMzU5NTlaMH8xCzAJBgNVBAYTAlVTMR0wGwYD
# VQQKExRTeW1hbnRlYyBDb3Jwb3JhdGlvbjEfMB0GA1UECxMWU3ltYW50ZWMgVHJ1
# c3QgTmV0d29yazEwMC4GA1UEAxMnU3ltYW50ZWMgQ2xhc3MgMyBTSEEyNTYgQ29k
# ZSBTaWduaW5nIENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAl4Me
# ABavLLHSCMTXaJNRYB5x9uJHtNtYTSNiarS/WhtR96MNGHdou9g2qy8hUNqe8+df
# J04LwpfICXCTqdpcDU6kDZGgtOwUzpFyVC7Oo9tE6VIbP0E8ykrkqsDoOatTzCHQ
# zM9/m+bCzFhqghXuPTbPHMWXBySO8Xu+MS09bty1mUKfS2GVXxxw7hd924vlYYl4
# x2gbrxF4GpiuxFVHU9mzMtahDkZAxZeSitFTp5lbhTVX0+qTYmEgCscwdyQRTWKD
# trp7aIIx7mXK3/nVjbI13Iwrb2pyXGCEnPIMlF7AVlIASMzT+KV93i/XE+Q4qITV
# RrgThsIbnepaON2b2wIDAQABo4IBgzCCAX8wLwYIKwYBBQUHAQEEIzAhMB8GCCsG
# AQUFBzABhhNodHRwOi8vczIuc3ltY2IuY29tMBIGA1UdEwEB/wQIMAYBAf8CAQAw
# bAYDVR0gBGUwYzBhBgtghkgBhvhFAQcXAzBSMCYGCCsGAQUFBwIBFhpodHRwOi8v
# d3d3LnN5bWF1dGguY29tL2NwczAoBggrBgEFBQcCAjAcGhpodHRwOi8vd3d3LnN5
# bWF1dGguY29tL3JwYTAwBgNVHR8EKTAnMCWgI6Ahhh9odHRwOi8vczEuc3ltY2Iu
# Y29tL3BjYTMtZzUuY3JsMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDAzAO
# BgNVHQ8BAf8EBAMCAQYwKQYDVR0RBCIwIKQeMBwxGjAYBgNVBAMTEVN5bWFudGVj
# UEtJLTEtNTY3MB0GA1UdDgQWBBSWO1PweTOXr32D7y4rzMq3hh5yZjAfBgNVHSME
# GDAWgBR/02Wnwt3su/AwCfNDOfoCrzMxMzANBgkqhkiG9w0BAQsFAAOCAQEAE4Ua
# HmmpN/egvaSvfh1hU/6djF4MpnUeeBcj3f3sGgNVOftxlcdlWqeOMNJEWmHbcG/a
# IQXCLnO6SfHRk/5dyc1eA+CJnj90Htf3OIup1s+7NS8zWKiSVtHITTuC5nmEFvwo
# sLFH8x2iPu6H2aZ/pFalP62ELinefLyoqqM9BAHqupOiDlAiKRdMh+Q6EV/WpCWJ
# mwVrL7TJAUwnewusGQUioGAVP9rJ+01Mj/tyZ3f9J5THujUOiEn+jf0or0oSvQ2z
# lwXeRAwV+jYrA9zBUAHxoRFdFOXivSdLVL4rhF4PpsN0BQrvl8OJIrEfd/O9zUPU
# 8UypP7WLhK9k8tAUITGCBHMwggRvAgEBMIGTMH8xCzAJBgNVBAYTAlVTMR0wGwYD
# VQQKExRTeW1hbnRlYyBDb3Jwb3JhdGlvbjEfMB0GA1UECxMWU3ltYW50ZWMgVHJ1
# c3QgTmV0d29yazEwMC4GA1UEAxMnU3ltYW50ZWMgQ2xhc3MgMyBTSEEyNTYgQ29k
# ZSBTaWduaW5nIENBAhBZhQi7tYqz1O1izDrs/nPdMAkGBSsOAwIaBQCggaYwGQYJ
# KoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEOMAwGCisGAQQB
# gjcCARUwIwYJKoZIhvcNAQkEMRYEFOVSDXQPL4fgJCGh0OA0VZT73IeqMEYGCisG
# AQQBgjcCAQwxODA2oBqAGABIAE8AQgAgAFMAbwBmAHQAdwBhAHIAZaEYgBZodHRw
# Oi8vd3d3LmhvYnNvZnQuY29tMA0GCSqGSIb3DQEBAQUABIIBAJ+hH327JWHAkWLm
# efs9WLrr5syvgdmjr/L/w3rltdOgsCxEqhUKuOULye7qMEwFix8HZpy/bfk8HVFG
# nUEYwCKWUhnTWbocC3sAm0uzu8zDeofSfSJUuWk+92Wm9kCS73Q0STtUH71kSYJe
# iodwBwGEM5nFD1p4TglIA7F3ZFmHffxYt6rwPTxMntAMsdp8uqfGEhVnJgwyFX2U
# aOQPhC1XiSrfEcsSFB8H0meVr20X6EgtDCT8NwFkhOe0MdsIpv7E5hwCvek590gH
# s1OQmsDoJ1VenpetcryiZyDLcqfF+ExtXGzoSeBUafpfJ3lBb4JZGdx8nH4Web4p
# GiCHOWqhggILMIICBwYJKoZIhvcNAQkGMYIB+DCCAfQCAQEwcjBeMQswCQYDVQQG
# EwJVUzEdMBsGA1UEChMUU3ltYW50ZWMgQ29ycG9yYXRpb24xMDAuBgNVBAMTJ1N5
# bWFudGVjIFRpbWUgU3RhbXBpbmcgU2VydmljZXMgQ0EgLSBHMgIQDs/0OMj+vzVu
# BNhqmBsaUDAJBgUrDgMCGgUAoF0wGAYJKoZIhvcNAQkDMQsGCSqGSIb3DQEHATAc
# BgkqhkiG9w0BCQUxDxcNMTgwNDE2MTIxNDIzWjAjBgkqhkiG9w0BCQQxFgQUgX+H
# eeJwYbdF9Rbpdn2K2Ey8UPIwDQYJKoZIhvcNAQEBBQAEggEALVkkdPMfaUQZMtlq
# pTVRjDGDHAIsDPFR2FNjCPHdcCsZ78uABMZHmNo0xnGUEz+N6BHAkSZjO/CVUKD2
# enQ91qoY0uj5TZmyUutvjPZV9/h+tArZGU0bMz61Lyya6qyaSn2HkiWFL4bODNYO
# nYbn7kry1H9s0ZYu3OjAMISRvlOqz4tkb4kGwl3hioBxBnnNv4x5mNLugSmNtF38
# UCGZ2DE/9AeM9oVwCMcQ+f8tunDDBzP1S6JLKyVDEIcebb71n9hvTvkJCO2qjyDv
# SEdDqs1/xdb65XIbc73agl2B4NnqgHgSIKhIZy5JiVVBvfkB/P1yL1Cc4Lw5Re7G
# wD/DgQ==
# SIG # End signature block
